--- Cluster Settings
SET CLUSTER SETTING ts.dedup.rule = 'keep.experimental';
SET CLUSTER SETTING sql.distsql.temp_storage.workmem = '4096Mib';
SET CLUSTER SETTING sql.all_push_down.enabled = true;
SET CLUSTER SETTING sql.pg_encode_short_circuit.enabled = true;
SET CLUSTER SETTING ts.parallel_degree = 8;
SET CLUSTER SETTING server.tsinsert_direct.enabled = true;


--- Time-Series
CREATE TS DATABASE runba;
-- USE runba;


CREATE TABLE runba.firegases00001 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20) NOT NULL,
  channel VARCHAR(20),
  companyid VARCHAR(20),
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  factory VARCHAR(20),
  msg VARCHAR(20),
  "name" VARCHAR(100),
  slaveid VARCHAR(10),
  "state" VARCHAR(20),
  "type" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  adr
);


CREATE TABLE runba.firegases450470 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20) NOT NULL,
  channel VARCHAR(20),
  companyid VARCHAR(20),
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  factory VARCHAR(20),
  msg VARCHAR(20),
  "name" VARCHAR(100),
  slaveid VARCHAR(10),
  "state" VARCHAR(20),
  "type" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  adr
);


CREATE TABLE runba.firegases451909 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20) NOT NULL,
  channel VARCHAR(20),
  companyid VARCHAR(20),
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  factory VARCHAR(20),
  msg VARCHAR(20),
  "name" VARCHAR(100),
  slaveid VARCHAR(10),
  "state" VARCHAR(20),
  "type" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  adr
);


CREATE TABLE runba.opcdata411 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20),
  channel VARCHAR(20) NOT NULL,
  companyid int NOT NULL,
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  device VARCHAR(100),
  deviceid VARCHAR(20),
  highmorewarn VARCHAR(20),
  highwarn VARCHAR(20),
  lowmorewarn VARCHAR(20),
  lowwarn VARCHAR(20),
  "name" VARCHAR(100),
  region VARCHAR(50),
  slaveid VARCHAR(100),
  "tag" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  channel,
  companyid
);


CREATE TABLE runba.opcdata449600 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20),
  channel VARCHAR(20) NOT NULL,
  companyid int NOT NULL,
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  device VARCHAR(100),
  deviceid VARCHAR(20),
  highmorewarn VARCHAR(20),
  highwarn VARCHAR(20),
  lowmorewarn VARCHAR(20),
  lowwarn VARCHAR(20),
  "name" VARCHAR(20),
  region VARCHAR(20),
  slaveid VARCHAR(100),
  "tag" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  channel,
  companyid
) ACTIVETIME 10m;


CREATE TABLE runba.opcdata449652 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20),
  channel VARCHAR(20) NOT NULL,
  companyid int NOT NULL,
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  device VARCHAR(100),
  deviceid VARCHAR(20),
  highmorewarn VARCHAR(20),
  highwarn VARCHAR(20),
  lowmorewarn VARCHAR(20),
  lowwarn VARCHAR(20),
  "name" VARCHAR(20),
  region VARCHAR(20),
  slaveid VARCHAR(100),
  "tag" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  channel,
  companyid
);


CREATE TABLE runba.opcdata450081 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20),
  channel VARCHAR(20) NOT NULL,
  companyid int NOT NULL,
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  device VARCHAR(100),
  deviceid VARCHAR(20),
  highmorewarn VARCHAR(20),
  highwarn VARCHAR(20),
  lowmorewarn VARCHAR(20),
  lowwarn VARCHAR(20),
  "name" VARCHAR(20),
  region VARCHAR(20),
  slaveid VARCHAR(100),
  "tag" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  channel,
  companyid
);


CREATE TABLE runba.opcdata451732 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  adr VARCHAR(20),
  channel VARCHAR(20) NOT NULL,
  companyid int NOT NULL,
  companyname VARCHAR(100),
  datatype VARCHAR(20),
  device VARCHAR(100),
  deviceid VARCHAR(20),
  highmorewarn VARCHAR(20),
  highwarn VARCHAR(20),
  lowmorewarn VARCHAR(20),
  lowwarn VARCHAR(20),
  "name" VARCHAR(100),
  region VARCHAR(50),
  slaveid VARCHAR(100),
  "tag" VARCHAR(20),
  unit VARCHAR(20)
) PRIMARY TAGS (
  channel,
  companyid
);


CREATE TABLE runba.t_399551 (
  "time" TIMESTAMPTZ NOT NULL,
  "value" FLOAT8 NULL
) TAGS (
  companyid VARCHAR(20) NOT NULL,
  companyname VARCHAR(100),
  slaveid VARCHAR(100)
) PRIMARY TAGS (
  companyid
);



--- Relational
CREATE DATABASE IF NOT EXISTS runba_tra;
-- USE runba_tra;


CREATE TABLE IF NOT EXISTS runba_tra.aqsc_donggongka (
  id INT4 NOT NULL,
  "from" VARCHAR(255) NOT NULL,
  type_id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  working_unit VARCHAR(255) NOT NULL,
  working_start INT4 NOT NULL,
  working_end INT4 NOT NULL,
  working_addr VARCHAR(255) NOT NULL,
  working_detail STRING NOT NULL,
  main_tools STRING NOT NULL,
  report_time INT4 NOT NULL,
  report_person_id VARCHAR(255) NULL,
  report_person VARCHAR(255) NOT NULL,
  "status" INT4 NOT NULL,
  cancel_status INT4 NOT NULL,
  current_users STRING NOT NULL,
  history_users STRING NOT NULL,
  is_reback INT4 NOT NULL,
  update_time INT4 NOT NULL,
  checked_status INT4 NOT NULL,
  is_third_part INT4 NOT NULL,
  safety_measure STRING NOT NULL,
  create_time INT4 NOT NULL,
  checked_user STRING NOT NULL,
  deal_status INT4 NOT NULL,
  user_id INT4 NOT NULL,
  qr_code VARCHAR(255) NOT NULL,
  check_current_users STRING NOT NULL,
  check_history_users STRING NOT NULL,
  second_type INT4 NOT NULL,
  is_verifying INT4 NOT NULL,
  examine_id INT4 NOT NULL,
  check_id INT4 NOT NULL,
  verification_type INT4 NOT NULL,
  qianyi_id INT4 NOT NULL,
  query_examine_id INT4 NOT NULL,
  has_interrupt INT4 NULL,
  has_resume INT4 NULL,
  has_delay INT4 NULL,
  is_report INT4 NULL,
  has_alert INT4 NOT NULL,
  history_alert INT4 NOT NULL,
  working_start_plan INT4 NULL,
  working_end_plan INT4 NULL,
  working_start_true INT4 NULL,
  working_end_true INT4 NULL,
  lng VARCHAR(255) NULL,
  lat VARCHAR(255) NULL,
  is_delete INT4 NOT NULL,
  cancel_reason VARCHAR(255) NOT NULL,
  uuid VARCHAR(50) NULL,
  access_pdf_url VARCHAR(255) NULL,
  pdf_url VARCHAR(255) NULL,
  has_command1 INT4 NOT NULL,
  has_command2 INT4 NOT NULL,
  has_command3 INT4 NOT NULL,
  has_command4 INT4 NOT NULL,
  check_device_name VARCHAR(100) NULL,
  check_work_name VARCHAR(100) NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    "from",
    type_id,
    company_id,
    company_name,
    working_unit,
    working_start,
    working_end,
    working_addr,
    working_detail,
    main_tools,
    report_time,
    report_person_id,
    report_person,
    "status",
    cancel_status,
    current_users,
    history_users,
    is_reback,
    update_time,
    checked_status,
    is_third_part,
    safety_measure,
    create_time,
    checked_user,
    deal_status,
    user_id,
    qr_code,
    check_current_users,
    check_history_users,
    second_type,
    is_verifying,
    examine_id,
    check_id,
    verification_type,
    qianyi_id,
    query_examine_id,
    has_interrupt,
    has_resume,
    has_delay,
    is_report,
    has_alert,
    history_alert,
    working_start_plan,
    working_end_plan,
    working_start_true,
    working_end_true,
    lng,
    lat,
    is_delete,
    cancel_reason,
    uuid,
    access_pdf_url,
    pdf_url,
    has_command1,
    has_command2,
    has_command3,
    has_command4,
    check_device_name,
    check_work_name
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.cd_behavior_area (
  id INT4 NOT NULL,
  area_name VARCHAR(255) NOT NULL,
  company_id INT4 NOT NULL,
  company_name VARCHAR(255) NULL,
  area_type INT4 NULL,
  coordinate VARCHAR(255) NOT NULL,
  is_select INT4 NULL,
  source INT4 NOT NULL,
  update_user_id INT4 NOT NULL,
  if_sync_position INT4 NOT NULL,
  style STRING NOT NULL,
  "3d_model_link" VARCHAR(500) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  if_display_datav INT4 NOT NULL,
  coordinate_wgs84 VARCHAR(255) NULL,
  coordinate_wgs84_lng VARCHAR(100) NULL,
  coordinate_wgs84_lat VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  remark VARCHAR(255) NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    area_name,
    company_id,
    company_name,
    area_type,
    coordinate,
    is_select,
    source,
    update_user_id,
    if_sync_position,
    style,
    "3d_model_link",
    create_time,
    update_time,
    if_display_datav,
    coordinate_wgs84,
    coordinate_wgs84_lng,
    coordinate_wgs84_lat,
    created_at,
    updated_at,
    remark
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.cd_device_point (
  id INT4 NOT NULL,
  point_name VARCHAR(500) NULL,
  adr VARCHAR(255) NULL,
  device_name VARCHAR(500) NULL,
  device_id INT4 NOT NULL,
  index_id INT4 NULL,
  index_upper_value DECIMAL(15, 6) NULL,
  index_lower_value DECIMAL(15, 6) NULL,
  company_id INT4 NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    point_name,
    adr,
    device_name,
    device_id,
    index_id,
    index_upper_value,
    index_lower_value,
    company_id,
    create_time,
    update_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.cd_security_device (
  id INT4 NOT NULL,
  manufacturer_id INT4 NOT NULL,
  "type" VARCHAR(255) NOT NULL,
  device_no VARCHAR(255) NOT NULL,
  device_name VARCHAR(255) NOT NULL,
  "status" INT4 NOT NULL,
  preview_url VARCHAR(255) NOT NULL,
  rec_url VARCHAR(255) NOT NULL,
  company_id INT4 NOT NULL,
  company_name VARCHAR(255) NULL,
  area_id INT4 NOT NULL,
  category INT4 NOT NULL,
  has_alert INT4 NOT NULL,
  gas_device_info VARCHAR(255) NOT NULL,
  channel_code VARCHAR(255) NOT NULL,
  realtime_play INT4 NOT NULL,
  realtime_category INT4 NOT NULL,
  ai_device_id INT4 NULL,
  style STRING NOT NULL,
  "3d_model_link" STRING NULL,
  coordinate STRING NOT NULL,
  display_type VARCHAR(255) NOT NULL,
  device_info_id INT4 NOT NULL,
  behavior_apply_status INT4 NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    manufacturer_id,
    "type",
    device_no,
    device_name,
    "status",
    preview_url,
    rec_url,
    company_id,
    company_name,
    area_id,
    category,
    has_alert,
    gas_device_info,
    channel_code,
    realtime_play,
    realtime_category,
    ai_device_id,
    style,
    "3d_model_link",
    coordinate,
    display_type,
    device_info_id,
    behavior_apply_status
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.cd_tijian_item_index (
  id INT4 NOT NULL,
  index_name VARCHAR(255) NOT NULL,
  index_unit VARCHAR(255) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    index_name,
    index_unit,
    create_time,
    update_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_company (
  company_id INT4 NOT NULL,
  index_show INT4 NOT NULL,
  account VARCHAR(50) NULL,
  code VARCHAR(25) NULL,
  qr_code BYTES NULL,
  "name" VARCHAR(150) NULL,
  short_name VARCHAR(150) NOT NULL,
  is_apply INT4 NOT NULL,
  "type" INT4 NOT NULL,
  "status" INT4 NOT NULL,
  status_update_time INT4 NOT NULL,
  license_src VARCHAR(250) NOT NULL,
  structure_src VARCHAR(250) NOT NULL,
  tax_src VARCHAR(250) NOT NULL,
  province INT4 NOT NULL,
  city INT4 NOT NULL,
  district INT4 NOT NULL,
  town INT4 NOT NULL,
  "address" VARCHAR(250) NOT NULL,
  office_call VARCHAR(20) NOT NULL,
  fax VARCHAR(20) NOT NULL,
  web_site VARCHAR(255) NOT NULL,
  zip_code INT4 NOT NULL,
  contact_person VARCHAR(50) NOT NULL,
  invite_company_id INT4 NOT NULL,
  create_time INT4 NOT NULL,
  create_user_id INT4 NOT NULL,
  update_time INT4 NOT NULL,
  update_user_id INT4 NOT NULL,
  logo VARCHAR(255) NOT NULL,
  sort INT4 NOT NULL,
  registration_code VARCHAR(40) NOT NULL,
  zhuce_code VARCHAR(255) NOT NULL,
  duty_company_type_id INT4 NOT NULL,
  residence VARCHAR(50) NOT NULL,
  registered_capital VARCHAR(50) NOT NULL,
  registered_capital_no INT4 NOT NULL,
  scope_business STRING NULL,
  registration_authority VARCHAR(50) NOT NULL,
  approved_date DECIMAL(10) NULL,
  registration_status INT4 NOT NULL,
  start_run_date DECIMAL(10) NULL,
  end_run_date DECIMAL(10) NULL,
  information_sources_id INT4 NOT NULL,
  information_update_date DECIMAL(10) NULL,
  company_source INT4 NOT NULL,
  is_register INT4 NOT NULL,
  zone_company_id INT4 NOT NULL,
  registration_time INT4 NOT NULL,
  registration_unit VARCHAR(50) NOT NULL,
  company_status INT4 NOT NULL,
  company_provider_type INT4 NOT NULL,
  revocation_time INT4 NOT NULL,
  annual_inspection_status INT4 NULL,
  total_amount_capital_contribution VARCHAR(50) NOT NULL,
  first_tax_year_month INT4 NULL,
  establishment_date INT4 NOT NULL,
  syn_from VARCHAR(255) NULL,
  syn_uid INT4 NOT NULL,
  industry_code VARCHAR(10) NULL,
  industry_name VARCHAR(10) NULL,
  aoic_id INT4 NULL,
  town_id INT4 NULL,
  ipo_id INT4 NULL,
  complete_time INT4 NOT NULL,
  is_complete INT4 NOT NULL,
  organization_code VARCHAR(250) NOT NULL,
  approve_applicant_status INT4 NOT NULL,
  approve_applicant_time INT4 NOT NULL,
  approve_applicant_remark VARCHAR(200) NOT NULL,
  "identity-font-card" VARCHAR(250) NOT NULL,
  "identity-back-card" VARCHAR(250) NOT NULL,
  apply_applicant_time INT4 NOT NULL,
  "version" INT4 NOT NULL,
  taxpayer_code VARCHAR(200) NOT NULL,
  tax VARCHAR(200) NOT NULL,
  vat_tax_type INT4 NOT NULL,
  is_empty_company INT4 NOT NULL,
  is_delete INT4 NOT NULL,
  delete_date INT4 NOT NULL,
  ser_processing_time INT4 NULL,
  ser_volume INT4 NULL,
  service_tag VARCHAR(255) NOT NULL,
  service_detail STRING NULL,
  has_ower INT4 NOT NULL,
  company_user_relation INT4 NOT NULL,
  inviter_user_id INT4 NOT NULL,
  active_code VARCHAR(10) NOT NULL,
  tenant_id INT4 NULL,
  tenant_name VARCHAR(255) NULL,
  tenant_admin_email VARCHAR(255) NULL,
  tenant_admin_phone VARCHAR(255) NULL,
  tenant_disabled INT4 NULL,
  approve_admin_time INT4 NOT NULL,
  approve_admin_remark VARCHAR(200) NOT NULL,
  contact VARCHAR(50) NOT NULL,
  contact_phone VARCHAR(25) NOT NULL,
  contact_email VARCHAR(250) NULL,
  contact_qq VARCHAR(25) NULL,
  contact_wechat VARCHAR(250) NULL,
  pid INT4 NULL,
  is_zone_company INT4 NULL,
  manual_audit_status INT4 NOT NULL,
  old_name VARCHAR(150) NULL,
  modify_time INT4 NULL,
  modify_user_id INT4 NULL,
  verify_status INT4 NOT NULL,
  verify_time INT4 NULL,
  verify_user_id INT4 NULL,
  business_information_complete INT4 NOT NULL,
  create_zone_company_id INT4 NOT NULL,
  has_requirement INT4 NOT NULL,
  add_reason INT4 NOT NULL,
  residence_mobile VARCHAR(25) NULL,
  administrator_mobile VARCHAR(25) NOT NULL,
  has_oa INT4 NOT NULL,
  "level" INT4 NOT NULL,
  tax_import_type INT4 NOT NULL,
  company_belong VARCHAR(255) NOT NULL,
  company_score INT4 NULL,
  success_service_count INT4 NULL,
  before_name VARCHAR(255) NOT NULL,
  taxpayer_num VARCHAR(255) NOT NULL,
  if_verified INT4 NOT NULL,
  verify_name VARCHAR(255) NOT NULL,
  hx_configid VARCHAR(255) NULL,
  industry_score INT4 NULL,
  percentile_score INT4 NULL,
  legal_type INT4 NULL,
  reg_number VARCHAR(50) NULL,
  industry VARCHAR(255) NULL,
  en_name VARCHAR(255) NULL,
  "tags" VARCHAR(255) NULL,
  org_approved_institute VARCHAR(255) NULL,
  province_short_name VARCHAR(50) NULL,
  org_number VARCHAR(50) NULL,
  gongshang_zhucecode VARCHAR(50) NULL,
  tax_code VARCHAR(255) NOT NULL,
  residence_id VARCHAR(255) NOT NULL,
  accountant VARCHAR(255) NOT NULL,
  accountant_mobile VARCHAR(255) NOT NULL,
  function_menu_url VARCHAR(255) NOT NULL,
  issue_date INT4 NOT NULL,
  min_pinpoint INT4 NULL,
  show_settle_type INT4 NULL,
  passport_id VARCHAR(50) NOT NULL,
  import_qua_area VARCHAR(255) NOT NULL,
  is_institution INT4 NOT NULL,
  tax_init INT4 NOT NULL,
  aqsc_update_time INT4 NOT NULL,
  balance DECIMAL(20, 2) NOT NULL,
  freezing_money DECIMAL(10, 2) NOT NULL,
  gs_caiji_time INT4 NULL,
  simple_desc STRING NOT NULL,
  register_time INT4 NOT NULL,
  id_num VARCHAR(50) NOT NULL,
  can_delete INT4 NOT NULL,
  can_not_delete_reason STRING NULL,
  update_business_info INT4 NULL,
  register_in_zone INT4 NOT NULL,
  stock_code VARCHAR(255) NOT NULL,
  has_system_role INT4 NOT NULL,
  user_create_default_role STRING NOT NULL,
  polyv_catid VARCHAR(255) NOT NULL,
  has_iot INT4 NULL,
  qianyi_id INT4 NOT NULL,
  threat_num_status INT4 NULL,
  central_point VARCHAR(255) NOT NULL,
  datav_logo VARCHAR(255) NOT NULL,
  datav_tilt INT4 NOT NULL,
  datav_redirect_host VARCHAR(255) NOT NULL,
  datav_screen_no INT4 NOT NULL,
  map_url VARCHAR(255) NOT NULL,
  rotation VARCHAR(255) NOT NULL,
  modelrotation VARCHAR(255) NOT NULL,
  pitch VARCHAR(255) NOT NULL,
  scale VARCHAR(255) NOT NULL,
  zoom VARCHAR(255) NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    company_id ASC
  ),
  FAMILY "primary" (
    company_id,
      index_show,
      account,
      code,
      qr_code,
      "name",
      short_name,
      is_apply,
      "type",
      "status",
      status_update_time,
      license_src,
      structure_src,
      tax_src,
      province,
      city,
      district,
      town,
      "address",
      office_call,
    fax,
    web_site,
    zip_code,
    contact_person,
    invite_company_id,
    create_time,
    create_user_id,
    update_time,
    update_user_id,
    logo,
    sort,
    registration_code,
    zhuce_code,
    duty_company_type_id,
    residence,
    registered_capital,
    registered_capital_no,
    scope_business,
    registration_authority,
    approved_date,
    registration_status,
    start_run_date,
    end_run_date,
    information_sources_id,
    information_update_date,
    company_source,
    is_register,
    zone_company_id,
    registration_time,
    registration_unit,
    company_status,
    company_provider_type,
    revocation_time,
    annual_inspection_status,
    total_amount_capital_contribution,
    first_tax_year_month,
    establishment_date,
    syn_from,
    syn_uid,
    industry_code,
    industry_name,
    aoic_id,
    town_id,
    ipo_id,
    complete_time,
    is_complete,
    organization_code,
    approve_applicant_status,
    approve_applicant_time,
    approve_applicant_remark,
    "identity-font-card",
    "identity-back-card",
    apply_applicant_time,
    "version",
    taxpayer_code,
    tax,
    vat_tax_type,
    is_empty_company,
    is_delete,
    delete_date,
    ser_processing_time,
    ser_volume,
    service_tag,
    service_detail,
    has_ower,
    company_user_relation,
    inviter_user_id,
    active_code,
    tenant_id,
    tenant_name,
    tenant_admin_email,
    tenant_admin_phone,
    tenant_disabled,
    approve_admin_time,
    approve_admin_remark,
    contact,
    contact_phone,
    contact_email,
    contact_qq,
    contact_wechat,
    pid,
    is_zone_company,
    manual_audit_status,
    old_name,
    modify_time,
    modify_user_id,
    verify_status,
    verify_time,
    verify_user_id,
    business_information_complete,
    create_zone_company_id,
    has_requirement,
    add_reason,
    residence_mobile,
    administrator_mobile,
    has_oa,
    "level",
    tax_import_type,
    company_belong,
    company_score,
    success_service_count,
    before_name,
    taxpayer_num,
    if_verified,
    verify_name,
    hx_configid,
    industry_score,
    percentile_score,
    legal_type,
    reg_number,
    industry,
    en_name,
    "tags",
    org_approved_institute,
    province_short_name,
    org_number,
    gongshang_zhucecode,
    tax_code,
    residence_id,
    accountant,
    accountant_mobile,
    function_menu_url,
    issue_date,
    min_pinpoint,
    show_settle_type,
    passport_id,
    import_qua_area,
    is_institution,
    tax_init,
    aqsc_update_time,
    balance,
    freezing_money,
    gs_caiji_time,
    simple_desc,
    register_time,
    id_num,
    can_delete,
    can_not_delete_reason,
    update_business_info,
    register_in_zone,
    stock_code,
    has_system_role,
    user_create_default_role,
    polyv_catid,
    has_iot,
    qianyi_id,
    threat_num_status,
    central_point,
    datav_logo,
    datav_tilt,
    datav_redirect_host,
    datav_screen_no,
    map_url,
    rotation,
    modelrotation,
    pitch,
    scale,
    zoom
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_datav_riskpoint_type (
  id INT4 NOT NULL,
  "level" INT4 NOT NULL,
  "type" INT4 NOT NULL,
  c INT4 NOT NULL,
  company_id INT4 NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    "level",
    "type",
    c,
    company_id
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_device_info (
  id INT4 NOT NULL,
  devicenumber VARCHAR(255) NOT NULL,
  usecernum VARCHAR(50) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  areacode VARCHAR(50) NOT NULL,
  townname VARCHAR(255) NOT NULL,
  companyname VARCHAR(255) NOT NULL,
  makecomname VARCHAR(255) NOT NULL,
  usestatus VARCHAR(50) NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  dangerflag VARCHAR(50) NOT NULL,
  jycomname VARCHAR(50) NOT NULL,
  result VARCHAR(50) NOT NULL,
  nextdate VARCHAR(50) NOT NULL,
  nextselfdate VARCHAR(50) NOT NULL,
  inspusestatus VARCHAR(50) NOT NULL,
  maintaincomname VARCHAR(255) NOT NULL,
  item_pk VARCHAR(255) NOT NULL,
  remark VARCHAR(255) NOT NULL,
  category1 VARCHAR(255) NOT NULL,
  category2 VARCHAR(255) NOT NULL,
  category3 VARCHAR(255) NOT NULL,
  company_id INT4 NOT NULL,
  qianyi_id INT4 NOT NULL,
  device_serial_number VARCHAR(255) NOT NULL,
  device_name_plate VARCHAR(255) NOT NULL,
  device_birth_number VARCHAR(255) NOT NULL,
  check_period INT4 NULL,
  check_period_unit VARCHAR(255) NULL,
  first_check_time VARCHAR(255) NULL,
  self_check_period INT4 NULL,
  self_check_period_unit VARCHAR(255) NULL,
  self_first_check_time VARCHAR(255) NULL,
  created_at INT4 NULL,
  updated_at INT4 NULL,
  area_id INT4 NOT NULL,
  if_sync_position INT4 NOT NULL,
  "3d_model_link" STRING NOT NULL,
  style STRING NOT NULL,
  nfc_id VARCHAR(255) NOT NULL,
  coordinate STRING NOT NULL,
  display_type VARCHAR(255) NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    devicenumber,
    usecernum,
    "name",
    areacode,
    townname,
    companyname,
    makecomname,
    usestatus,
    "address",
    dangerflag,
    jycomname,
    result,
    nextdate,
    nextselfdate,
    inspusestatus,
    maintaincomname,
    item_pk,
    remark,
    category1,
    category2,
    category3,
    company_id,
    qianyi_id,
    device_serial_number,
    device_name_plate,
    device_birth_number,
    check_period,
    check_period_unit,
    first_check_time,
    self_check_period,
    self_check_period_unit,
    self_first_check_time,
    created_at,
    updated_at,
    area_id,
    if_sync_position,
    "3d_model_link",
    style,
    nfc_id,
    coordinate,
    display_type
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_drill (
  id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  company_name VARCHAR(500) NOT NULL,
  "name" VARCHAR(500) NOT NULL,
  drill_plan_id INT4 NOT NULL,
  drill_plan_theme_id VARCHAR(500) NOT NULL,
  category INT4 NOT NULL,
  start_time INT4 NOT NULL,
  end_time INT4 NOT NULL,
  org_department VARCHAR(500) NOT NULL,
  attend_department VARCHAR(500) NOT NULL,
  place VARCHAR(500) NOT NULL,
  attend_person_num INT4 NOT NULL,
  process_description STRING NULL,
  general_director VARCHAR(500) NOT NULL,
  general_director_job VARCHAR(500) NOT NULL,
  general_planner VARCHAR(500) NOT NULL,
  general_planner_job VARCHAR(500) NOT NULL,
  is_assess INT4 NULL,
  is_del INT4 NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    company_id,
    company_name,
    "name",
    drill_plan_id,
    drill_plan_theme_id,
    category,
    start_time,
    end_time,
    org_department,
    attend_department,
    place,
    attend_person_num,
    process_description,
    general_director,
    general_director_job,
    general_planner,
    general_planner_job,
    is_assess,
    is_del,
    created_at,
    updated_at
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_drill_plan (
  id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  plan_count INT4 NOT NULL,
  "status" INT4 NOT NULL,
  repeal_cause VARCHAR(500) NULL,
  repeal_user_id INT4 NOT NULL,
  repeal_user_name VARCHAR(500) NULL,
  repeal_time INT4 NULL,
  is_sign INT4 NOT NULL,
  copy_num INT4 NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    company_id,
    company_name,
    "name",
    plan_count,
    "status",
    repeal_cause,
    repeal_user_id,
    repeal_user_name,
    repeal_time,
    is_sign,
    copy_num,
    created_at,
    updated_at
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_drill_plan_theme (
  id INT4 NOT NULL,
  drill_plan_id INT4 NOT NULL,
  theme VARCHAR(255) NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  category INT4 NOT NULL,
  "year" VARCHAR(255) NOT NULL,
  "month" VARCHAR(255) NOT NULL,
  content STRING NULL,
  "sort" INT4 NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    drill_plan_id,
    theme,
    "address",
    category,
    "year",
    "month",
    content,
    "sort",
    created_at,
    updated_at
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_risk_analyse_objects (
  id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  obj_name VARCHAR(50) NOT NULL,
  obj_code VARCHAR(45) NULL,
  "level" VARCHAR(50) NOT NULL,
  category INT4 NULL,
  create_user_id INT4 NOT NULL,
  create_user_nickname VARCHAR(255) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  danger_source VARCHAR(255) NOT NULL,
  danger_code VARCHAR(255) NOT NULL,
  danger_level VARCHAR(255) NOT NULL,
  chemical_name VARCHAR(255) NOT NULL,
  chemical_attribute VARCHAR(255) NOT NULL,
  chemical_cas VARCHAR(255) NOT NULL,
  chemical_technique VARCHAR(255) NOT NULL,
  chemical_storage VARCHAR(255) NOT NULL,
  technique_name VARCHAR(255) NOT NULL,
  technique_code VARCHAR(255) NOT NULL,
  technique_device VARCHAR(255) NOT NULL,
  technique_address VARCHAR(255) NOT NULL,
  location_name VARCHAR(255) NOT NULL,
  location_code VARCHAR(255) NOT NULL,
  location_category VARCHAR(255) NOT NULL,
  location_company_category VARCHAR(255) NOT NULL,
  location_technique VARCHAR(255) NOT NULL,
  risk_status INT4 NULL,
  risk_type INT4 NULL,
  is_access INT4 NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC),
  FAMILY "primary" (
    id,
    company_id,
    obj_name,
    obj_code,
    "level",
    category,
    create_user_id,
    create_user_nickname,
    create_time,
    update_time,
    danger_source,
    danger_code,
    danger_level,
    chemical_name,
    chemical_attribute,
    chemical_cas,
    chemical_technique,
    chemical_storage,
    technique_name,
    technique_code,
    technique_device,
    technique_address,
    location_name,
    location_code,
    location_category,
    location_company_category,
    location_technique,
    risk_status,
    risk_type,
    is_access
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_risk_area (
  id INT4 NOT NULL,
  risk_id INT4 NOT NULL,
  area_id INT4 NOT NULL,
  "desc" VARCHAR(255) NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    risk_id,
    area_id,
    "desc",
    create_time,
    update_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_risk_point (
  id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  user_id INT4 NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "type" INT4 NOT NULL,
  activity_type INT4 NOT NULL,
  tszy_activity_type VARCHAR(255) NOT NULL,
  device_name VARCHAR(255) NOT NULL,
  "status" INT4 NOT NULL,
  "level" INT4 NOT NULL,
  create_time INT4 NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    company_id,
    user_id,
    "name",
    "type",
    activity_type,
    tszy_activity_type,
    device_name,
    "status",
    "level",
    create_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_tijian_item (
  id INT4 NOT NULL,
  item VARCHAR(50) NOT NULL,
  content STRING NOT NULL,
  company_id INT4 NOT NULL,
  create_user_id INT4 NOT NULL,
  create_time INT4 NOT NULL,
  update_time INT4 NOT NULL,
  is_common INT4 NOT NULL,
  card_template_id INT4 NOT NULL,
  card_template_name VARCHAR(255) NOT NULL,
  period_id INT4 NULL,
  qianyi_id INT4 NOT NULL,
  check_type INT4 NOT NULL,
  index_id INT4 NOT NULL,
  measure STRING NOT NULL,
  source_from INT4 NOT NULL,
  template_type INT4 NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    item,
    content,
    company_id,
    create_user_id,
    create_time,
    update_time,
    is_common,
    card_template_id,
    card_template_name,
    period_id,
    qianyi_id,
    check_type,
    index_id,
    measure,
    source_from,
    template_type
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_tijian_item_index (
  id INT4 NOT NULL,
  index_name VARCHAR(255) NOT NULL,
  index_unit VARCHAR(255) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  FAMILY "primary" (
    id,
    index_name,
    index_unit,
    create_time,
    update_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_tijiancard_item_relation (
  id INT4 NOT NULL,
  company_id INT4 NOT NULL,
  tijiancard_id VARCHAR(50) NOT NULL,
  item_ids STRING NOT NULL,
  obj_type INT4 NOT NULL,
  obj_id INT4 NOT NULL,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL,
  delete_time INT4 NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    id ASC
  ),
  INDEX tijian_id_relation (
    tijiancard_id ASC
  ),
  FAMILY "primary" (
    id,
    company_id,
    tijiancard_id,
    item_ids,
    obj_type,
    obj_id,
    create_time,
    update_time,
    delete_time
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.plat_zone_member (
  member_id INT4 NOT NULL,
  member_code VARCHAR(20) NOT NULL,
  member_name VARCHAR(50) NOT NULL,
  member_type INT4 NOT NULL,
  "contract" VARCHAR(50) NULL,
  "position" VARCHAR(50) NULL,
  contract_call VARCHAR(30) NULL,
  contract_mobile VARCHAR(20) NOT NULL,
  contract_email VARCHAR(100) NULL,
  invite_status INT4 NOT NULL,
  invite_operate_status INT4 NOT NULL,
  invite_operate_open_time INT4 NOT NULL,
  enterprise_status INT4 NULL,
  company_id INT4 NOT NULL,
  zone_company_id INT4 NOT NULL,
  rel_status INT4 NOT NULL,
  join_time INT4 NOT NULL,
  remove_time INT4 NOT NULL,
  create_time INT4 NOT NULL,
  create_user_id INT4 NULL,
  update_time INT4 NULL,
  update_user_id INT4 NULL,
  invite_date INT4 NOT NULL,
  invite_count INT4 NOT NULL,
  introducing_way INT4 NOT NULL,
  sys_investment_workplace_id INT4 NOT NULL,
  sys_investment_people_id INT4 NOT NULL,
  investment_type_id INT4 NULL,
  company_type_id INT4 NULL,
  investment_date INT4 NULL,
  expand_city_id INT4 NOT NULL,
  add_type INT4 NOT NULL,
  "status" INT4 NOT NULL,
  zhuce_code VARCHAR(50) NOT NULL,
  archives_code VARCHAR(50) NOT NULL,
  is_history_rel INT4 NOT NULL,
  agency_id INT4 NOT NULL,
  pic1_url VARCHAR(255) NOT NULL,
  pic1_down_times INT4 NOT NULL,
  pic1_upload_time TIMESTAMP NULL,
  pic2_url VARCHAR(255) NOT NULL,
  pic2_down_times INT4 NOT NULL,
  pic2_upload_time TIMESTAMP NULL,
  pic3_url VARCHAR(255) NOT NULL,
  pic3_down_times INT4 NOT NULL,
  pic3_upload_time TIMESTAMP NULL,
  pic4_url VARCHAR(255) NOT NULL,
  pic4_down_times INT4 NOT NULL,
  pic4_upload_time TIMESTAMP NULL,
  pic5_url VARCHAR(255) NOT NULL,
  pic5_down_times INT4 NOT NULL,
  pic5_upload_time TIMESTAMP NULL,
  new_taxpayer INT4 NOT NULL,
  effective_taxpayer INT4 NOT NULL,
  total_tax DECIMAL(20, 2) NOT NULL,
  company_type INT4 NOT NULL,
  is_virtual_member INT4 NOT NULL,
  new_taxpayer_month INT4 NULL,
  effective_taxpayer_month INT4 NULL,
  has_return_tax INT4 NULL,
  "level" INT4 NOT NULL,
  is_member INT4 NOT NULL,
  join_error_msg VARCHAR(255) NOT NULL,
  admin_user_id INT4 NOT NULL,
  return_tax_limit INT4 NOT NULL,
  leader_name VARCHAR(255) NOT NULL,
  leader_tel VARCHAR(255) NOT NULL,
  trade_type INT4 NOT NULL,
  move_in_type INT4 NOT NULL,
  expense_management_time INT4 NOT NULL,
  introduce_investment_people_id INT4 NOT NULL,
  company_belong VARCHAR(255) NOT NULL,
  residence_id VARCHAR(255) NOT NULL,
  passport_id VARCHAR(50) NOT NULL,
  accountant VARCHAR(255) NOT NULL,
  accountant_mobile VARCHAR(255) NOT NULL,
  administrator_mobile VARCHAR(25) NOT NULL,
  "tag" VARCHAR(255) NOT NULL,
  company_category VARCHAR(255) NOT NULL,
  register_in_zone INT4 NOT NULL,
  business_information_complete INT4 NOT NULL,
  qianyi_id INT4 NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (
    member_id ASC
  ),
  FAMILY "primary" (
    member_id,
    member_code,
    member_name,
    member_type,
    "contract",
    "position",
    contract_call,
    contract_mobile,
    contract_email,
    invite_status,
    invite_operate_status,
    invite_operate_open_time,
    enterprise_status,
    company_id,
    zone_company_id,
    rel_status,
    join_time,
    remove_time,
    create_time,
    create_user_id,
    update_time,
    update_user_id,
    invite_date,
    invite_count,
    introducing_way,
    sys_investment_workplace_id,
    sys_investment_people_id,
    investment_type_id,
    company_type_id,
    investment_date,
    expand_city_id,
    add_type,
    "status",
    zhuce_code,
    archives_code,
    is_history_rel,
    agency_id,
    pic1_url,
    pic1_down_times,
    pic1_upload_time,
    pic2_url,
    pic2_down_times,
    pic2_upload_time,
    pic3_url,
    pic3_down_times,
    pic3_upload_time,
    pic4_url,
    pic4_down_times,
    pic4_upload_time,
    pic5_url,
    pic5_down_times,
    pic5_upload_time,
    new_taxpayer,
    effective_taxpayer,
    total_tax,
    company_type,
    is_virtual_member,
    new_taxpayer_month,
    effective_taxpayer_month,
    has_return_tax,
    "level",
    is_member,
    join_error_msg,
    admin_user_id,
    return_tax_limit,
    leader_name,
    leader_tel,
    trade_type,
    move_in_type,
    expense_management_time,
    introduce_investment_people_id,
    company_belong,
    residence_id,
    passport_id,
    accountant,
    accountant_mobile,
    administrator_mobile,
    "tag",
    company_category,
    register_in_zone,
    business_information_complete,
    qianyi_id
  )
);


CREATE TABLE IF NOT EXISTS runba_tra.testa (
  a INT4 NULL,
  b VARCHAR(20) NULL,
  FAMILY "primary" (
    a,
    b,
    rowid
  )
);
